coverage:
  if: true
codeToTestRatio:
  code:
    - 'src/**/*.ts'
    - '!src/__tests__/**/*.ts'
  test:
    - 'src/__tests__/**/*.ts'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
badges:
  datastores:
    - local://badges
push:
  enable: true
